import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bianca AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  const isDev = process.env.NODE_ENV === 'development'

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={isDev}>{children}</body>
    </html>
  )
}
